name: Run test and verifier

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.33.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: apk add python3 python3-dev py3-pip bash libxml2-dev libxslt-dev build-base
    - name: Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Install Crystal dependencies
      run: shards
    - name: Run tests
      run: crystal spec --verbose
    - name: Run verifier
      run: find atcoder -name "*.verify.cr" | xargs oj-verify run
    - name: Run linter
      run: bin/ameba
