name: Run test and verifier

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.33.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: apk add python3 python3-dev py3-pip bash libxml2-dev libxslt-dev build-base
    - name: Install pip dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
    - name: Install Crystal dependencies
      run: shards
    - name: Run tests
      run: crystal spec --verbose
    - name: Run verifier
      run: oj-verify run
    - name: Run linter
      run: bin/ameba
    - name: Build docs
      run: git ls-files atcoder | grep -v test | grep -v bench | xargs crystal docs -o dist 
    - name: Deploy docs to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
