name: Run test and verifier

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal:0.33.0-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: apk add python3 py3-pip bash
    - name: Install pip dependencies
      run: pip install -r requirements.txt
    - name: Run tests
      run: crystal spec --verbose
    - name: Run verifier
      run: find atcoder -name "*.verify.cr" | xargs oj-verify run
